# Generated by Django 5.1.5 on 2025-01-27 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
