# Generated by Django 5.1.5 on 2025-01-27 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_custom_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
