# Generated by Django 5.1.5 on 2025-01-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='roomid',
        ),
    ]
