# Generated by Django 5.1.5 on 2025-01-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_roomid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='userid',
            new_name='user',
        ),
    ]
