# Generated by Django 5.1.5 on 2025-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_userid_chatroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='senderid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
