# Generated by Django 5.1.5 on 2025-01-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_senderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
    ]
