# Generated by Django 5.1.5 on 2025-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='history',
            field=models.TextField(null=True),
        ),
    ]
